/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config dist/server/wrangler.json worker-configuration.d.ts --include-runtime false` (hash: cd2c420ee87ca98b6086802a27fb2254)
interface __BaseEnv_Env {
	ENGAGEMENT: AnalyticsEngineDataset;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
