/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config dist/server/wrangler.json worker-configuration.d.ts --include-runtime false` (hash: ae671d6484d9cda1f0d7d98e922961b5)
interface __BaseEnv_Env {
	JOURNEY_ARCHIVE: R2Bucket;
	JOURNEYS: D1Database;
	ENGAGEMENT: AnalyticsEngineDataset;
	JOURNEY_RATE: RateLimit;
	JOURNEY_GLOBAL_RATE: RateLimit;
	JOURNEYS_ENABLED: "1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "JOURNEYS_ENABLED">> {}
}
