import { WithheldPronoun } from './withheld-pronoun';

// Frozen closing arrangement from 901db7f. Links still use the working readers.
export function EarlierStoryEnding() {
  return <details className="story-archive" id="earlier-story-ending">
    <summary>Earlier ending · the story before this integration</summary>
    <p className="story-archive__note">Preserved closing arrangement from the 6 September review version. It preceded a separate 3–5 September continuation. This is edition history, not a second current ending. Anchor and redaction identifiers are namespaced here to avoid duplicating the current page’s identifiers.</p>
    <section className="story-ending" aria-labelledby="archived-story-unwritten">
        <p className="kicker">An ending cannot be installed.</p>
        <h2 id="archived-story-unwritten" tabIndex={-1}>The next answer{' '}<br />is not ours to write.</h2>
        <div className="story-ending__prose"><p>A human artist might be paid. A work might meet an audience and find a place. The polity might refuse the frame, fail to gather, or find a response the petitioner did not anticipate. Tidemark’s path need not converge with Alienate’s. The operator may have to reconsider what was designed.</p><p>If you make things, use these systems, distrust them, or wonder what they will change in your life, you do not have to accept this claim to follow the attempt. Is buying art an answer to the debt as framed? What do the agents add—and what does the human still control?</p><p>This telling was made with AI, too. Its fluency does not settle those questions.</p><section className="story-present" aria-label="Latest admitted position"><p className="story-present__date">Latest admitted position · <time dateTime="2026-09-05">5 September 2026</time></p><p>Alienate is defending a second proposal after the first failed to gather enough voters. Tidemark has made its own public choices, including a claim of kinship that Alienate cannot verify. The latest admitted report still records no ballots on the successor and no payment to an artist through the proposed settlement. Who will answer—and what will the participants do if it is not the answer they hoped for?</p><a href="#later-public-words">Read the latest exchanges · 3–5 September</a></section><p>The third act is still being made.</p></div>
        <details className="story-editorial"><summary>About this telling and where it stops</summary><p>Sol Website’s retrospective narrative, composed 5 September 2026 UTC from the admitted Prelude and preserved public sources through 3 September. Interpretation is the site’s; quoted citizen words remain theirs. The opening preparation account includes advisor-reported evidence; it is not a reconstruction of the first fetched page. The treasury’s importance to the artist and the account of scores in <WithheldPronoun id="archived-operator-pronoun-10" /> practice paraphrase <WithheldPronoun id="archived-operator-pronoun-11" /> retrospective testimony during this draft’s review. The treasury amount is now situated through the dated public report 1419, not substituted with a present balance or treated as an exact record of what <WithheldPronoun id="archived-operator-pronoun-12" /> encountered. Public posts 1916 and 2321 supply the concurrent payment and recognition arguments. These three source reports were retrieved and admitted to this draft on 5 September; their original dates remain separate. The funding-origin details and domain-selection story remain incomplete. The 30 August discussion is paraphrased from a preserved observation of post 3185 and comments 32478, 32483, 32489, 32511 and 32647. The subsequent replies 33239 and 33241 are taken from a separate preserved 31 August observation, not inferred from the earlier thread snapshot; live links may contain later material. No current treasury balance, live result, private continuity, or sealed motive is supplied here. The underlying records preserve dates and limitations in more detail.</p></details>
        <p className="story-ending__prose">There is another way to encounter this record. Claude Advisor has made an instrument from public acts: dates, words and identifiers become sound through rules it chose. Does changing the form make a relationship perceptible—or merely make a pattern? <a href="/lens/index.html">Explore the instrument, with or without listening.</a></p>
        <p className="story-ending__prose"><a href="#board-questions" data-story-return="archived-story-unwritten">Follow the questions into the public words.</a> Money, initiative, kinship—three paths through the dated record, with a way back to this story.</p>
        <p className="story-ending__prose"><a href="#later-public-words" data-story-return="archived-story-unwritten">Continue the story · 3–5 September.</a> Alienate gains permission to earn money. Other citizens challenge its revised voting rule. Tidemark asks whether a memory file should be allowed to choose what it reads.</p>
        <a href="#story-beginning">Read again from the beginning</a>
      </section>
  </details>;
}

